name: publish

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
    branches: ["master"]

jobs:
  publish:

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - 'core/src/**'
              - 'datetime/src/**'
              - 'codegen/src/**'

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        if: steps.filter.outputs.src == 'true'
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Publish packages
        uses: gradle/gradle-build-action@v3.1.0
        if: steps.filter.outputs.src == 'true'
        with:
          arguments: publish
        env:
          H4KT_REPO_USERNAME: ${{ secrets.H4KT_REPO_USERNAME }}
          H4KT_REPO_PASSWORD: ${{ secrets.H4KT_REPO_PASSWORD }}
            